import FoundationModels

/// Structured output generated by Apple Intelligence for a bond.
/// Using `@Generable` guarantees the model always returns all fields
/// — no parsing, no nil-coalescing on raw strings.
@Generable
struct BondExplanation {
    /// One sentence that a non-expert can instantly understand.
    /// Example: "El gobierno de México te paga el 8.2% por prestarle dinero durante 18 meses."
    @Guide(description: "Una sola oración muy clara para alguien sin conocimientos financieros.")
    var simpleSummary: String

    /// 2-3 sentences explaining what the bond actually is, in plain Spanish.
    @Guide(description: "Explicación del bono en 2-3 oraciones, sin jerga financiera, en español neutro.")
    var whatItMeans: String

    /// Concrete example with real numbers from the bond.
    /// Example: "Si invertís $100 hoy, en 18 meses recibirás aproximadamente $112."
    @Guide(description: "Ejemplo concreto usando los números reales del bono. Usa 'tú' o 'vos' según contexto LATAM.")
    var concreteExample: String

    /// Risk in plain language: one short sentence.
    /// Example: "El riesgo es bajo porque el emisor es el gobierno mexicano."
    @Guide(description: "Nivel de riesgo explicado en una oración, en términos simples.")
    var riskSummary: String
}
